name: Sync + Release

on:
  repository_dispatch:
    types: [sync_release]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Sync with upstream + Release
      run: ./.github/sync_release.sh the80scomputers@gmail.com theypsilon@gmail.com
      env:
        NOTIFICATION_API_KEY: ${{ secrets.NOTIFICATION_API_KEY }}
